### ISSUE TITLE
Wrapper for the a tabbed formspec

### ISSUE THREAD

**Issue by Ryan-Nolan** [minetest-mods/smartfs#7] opened 2015-04-28 15:54 UTC
Hi, would be nice if someone could create a wrapper for a tabbed formspec.

Im currently playing around with ideas but this is the first time ive attempted to create tabbed form specs so its still new to me.

Once ive figured it il attempt to create a smartfs wrapper for it if no one else hasn't already done it :)

**Comment by crazyR14** [comment] 2015-04-28 16:01
something like:

```lua
state:tabbed( x,y,name,tabs,current_tab,transparent,drawborder )
```

tabs would be a table like so:

```lua
tabs = {
    tab_title = function_that_contains_tab_content(),
    tab_title_2 = function_that_contains_tab_content_2(),
    tab_title_3 = function_that_contains_tab_content_3(),
}
```

**Comment by rubenwardy** [comment] 2015-04-28 16:44
maybe:
```Lua
local tabset = state:tabset(x, y, name, etc)
tabset.add("tabname", function(self)
     self:button(x, y, text, etc)
end))
local t1 = tabset.add("tabname2", function(self)
     self:button(x, y, text, etc)
end))
t1:select()
```

**Comment by crazyR14** [comment] 2015-04-28 16:53
^ +1 that would work nicely. just as a side note you may wanna have a look at this....
it looks like it has been similarly for the builtin main menu lol:

https://github.com/minetest/minetest/blob/master/builtin/mainmenu/init.lua#L123
https://github.com/minetest/minetest/blob/master/builtin/fstk/tabview.lua

**Comment by bell07** [comment] 2016-10-25 15:02
The first step is to implement a "hidden" attribute to the elements. So the tabbed functionality can be done by hidding the elements at other not visible bars.
The second step is to implement a "view"-element, that contains a own element-list as attribute, does handle the x/y and size offsets between view and view-elements in the build() and handle the view-prefix in submit() to get explicit fields assignment. If view is implemented it will be possible to set all not loaded tab-contents to invisible at once.
Maybe the views could be stacked (view in a view in a view...).
The tab's header /switching should be implemented by application because of different gusto. The simplest implementation is the implemented "toggle" button ;)

**Comment by bell07** [comment] 2016-10-28 09:14
I did it! See commit: https://github.com/bell07/minetest-smartfs/commit/f438dd5ddb27b93a417d61af6d4ffbb0feedd929

there is a example of tab implementaton: https://github.com/bell07/minetest-smartfs/blob/views/example-views.lua#L82

Documentation still to be done :( 

Because of more testing is needed I did not open a pull request. Or should I do it? (github newbie)

**Comment by bell07** [comment] 2018-01-26 12:47
The views branch is merged in the meantime. Is the enhancement enough and we can close this issue?

**Comment by bell07** [comment] 2018-08-27 18:09
Closed because of no response about implemented way. Assume the issue is solved

**Closed by bell07** 2018-08-27 18:09 UTC
Labels: enhancement
